# Generated by Django 4.1.3 on 2022-12-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
