# Generated by Django 4.1.3 on 2022-12-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_useraccount_photo_alter_useraccount_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='photo',
            field=models.ImageField(blank=True, default='static/user_profile_picture/default.png', null=True, upload_to='static/user_profile_picture'),
        ),
    ]
