# Generated by Django 4.1.3 on 2022-12-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_useraccount_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='photo',
            field=models.ImageField(blank=True, default='user_picture/default.png', null=True, upload_to='user_picture/'),
        ),
    ]
