# Generated by Django 4.1.3 on 2022-12-03 14:33

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_useraccount_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='photo',
            field=models.ImageField(blank=True, default='user_picture/default.png', null=True, storage=authentication.models.OverwriteStorage(), upload_to='user_picture/'),
        ),
    ]
