# Generated by Django 4.1.3 on 2022-12-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetestmodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/test'),
        ),
    ]
