# Generated by Django 4.1.3 on 2022-12-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_alter_imagetestmodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetestmodel',
            name='img',
            field=models.ImageField(upload_to='static/images/test'),
        ),
    ]
