# Generated by Django 4.1.3 on 2022-12-03 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_alter_imagetestmodel_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageTestModel',
        ),
    ]
