# Generated by Django 4.1.3 on 2022-12-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upimage',
            name='tipe',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
