# Generated by Django 4.1.3 on 2022-12-03 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0006_upimage_tipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpImage',
        ),
    ]
